# Generated by Django 5.2.9 on 2026-03-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auto",
            old_name="name",
            new_name="nickname",
        ),
    ]
